### Data Cleaning for the Historical Alarm Tag Dataset from category 1


Alarm Description: Generator 1 was stopped by a mechanical emergency stop (QSD)

The following preprocessing steps were performed:
1) Loaded the raw alarm log data.
2) Selected the relevant columns and removed unit columns.
3) Converted the DateTime column from object to datetime format.
4) Converted values to string format using astype(str).
5) Replaced comma decimal separators with dots using str.replace(',', '.').
6) Checked for missing values.
7) Checked for duplicate records.
8) Exported the cleaned dataset.

In [1]:
import pandas as pd

In [ ]:
## get the file_path of the dataset
file_path = r"E:\code\Clean_HistData\final_Hist_data\raw data\KONTROLL_HURTIGSTOPP_MEK_AL.csv"

In [ ]:
# diaplay the dataset in a pandas dataframe

historic_data = pd.read_csv(file_path,sep=";",dtype=str,engine="python")
historic_data.shape  # get  the shape of dataset

(8785, 11)

In [9]:
historic_data.head(5)  # shows the first 5 rows of dataset

,DateTime,Value (Cluster1.OGREY1_G1_KONTROLL_REG_P_SP_SP_LAST),Unit (Cluster1.OGREY1_G1_KONTROLL_REG_P_SP_SP_LAST),Value (Cluster1.OGREY1_G1_KONTROLL_REG_NIVA_SP_SP_LAST),Unit (Cluster1.OGREY1_G1_KONTROLL_REG_NIVA_SP_SP_LAST),Value (Cluster1.OGREY1_G1_KONTROLL_REG_NIVA_SP_TM_PV),Unit (Cluster1.OGREY1_G1_KONTROLL_REG_NIVA_SP_TM_PV),Value (Cluster1.OGREY1_G1_KONTROLL_REG_P_SP_TM_PV),Unit (Cluster1.OGREY1_G1_KONTROLL_REG_P_SP_TM_PV),Value (Cluster1.OGREY1_G1_KONTROLL_AGC_DB_SP),Unit (Cluster1.OGREY1_G1_KONTROLL_AGC_DB_SP)
0,2023-12-31 23:00:00.000,8200,kW,"-0,5",m,"-0,5",m,600,kW,0,NaN
1,2024-01-01 00:00:00.000,8200,kW,"-0,5",m,"-0,5",m,"4264,748807683333",kW,"5,475555462666667",NaN
2,2024-01-01 01:00:00.000,8200,kW,"-0,5",m,"-0,5",m,5600,kW,"5,599999905",NaN
3,2024-01-01 02:00:00.000,8200,kW,"-0,5",m,"-0,5",m,"5503,84444445",kW,"5,502222220116667",NaN
4,2024-01-01 03:00:00.000,8200,kW,"-0,5",m,"-0,5",m,5500,kW,"5,5",NaN

In [ ]:
# # get the more information about the dataset ( feature names, missing value count and data type)

historic_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8785 entries, 0 to 8784
Data columns (total 11 columns):
 #   Column                                                   Non-Null Count  Dtype
---  ------                                                   --------------  -----
 0   DateTime                                                 8785 non-null   object
 1   Value (Cluster1.OGREY1_G1_KONTROLL_REG_P_SP_SP_LAST)     8650 non-null   object
 2   Unit (Cluster1.OGREY1_G1_KONTROLL_REG_P_SP_SP_LAST)      8785 non-null   object
 3   Value (Cluster1.OGREY1_G1_KONTROLL_REG_NIVA_SP_SP_LAST)  8651 non-null   object
 4   Unit (Cluster1.OGREY1_G1_KONTROLL_REG_NIVA_SP_SP_LAST)   8785 non-null   object
 5   Value (Cluster1.OGREY1_G1_KONTROLL_REG_NIVA_SP_TM_PV)    5991 non-null   object
 6   Unit (Cluster1.OGREY1_G1_KONTROLL_REG_NIVA_SP_TM_PV)     8785 non-null   object
 7   Value (Cluster1.OGREY1_G1_KONTROLL_REG_P_SP_TM_PV)       6663 non-null   object
 8   Unit (Cluster1.OGREY1_G1_KONTROLL_REG_P_SP_TM_PV)        8785 non-null   object
 9   Value (Cluster1.OGREY1_G1_KONTROLL_AGC_DB_SP)            8784 non-null   object
 10  Unit (Cluster1.OGREY1_G1_KONTROLL_AGC_DB_SP)             0 non-null      object
dtypes: object(11)
memory usage: 755.1+ KB

In [11]:

# Make a working copy
analys_historic_data= historic_data.copy()

In [ ]:
# Since there are separate columns for each feature, representing units, we remove those unit columns to keep the dataset clean

analys_historic_data= analys_historic_data.loc[:, ~analys_historic_data.columns.str.contains("Unit", case=False)]

In [ ]:
# after removing the  Unit colums so the number of columns become 6
analys_historic_data.columns

Index(['DateTime', 'Value (Cluster1.OGREY1_G1_KONTROLL_REG_P_SP_SP_LAST)',
       'Value (Cluster1.OGREY1_G1_KONTROLL_REG_NIVA_SP_SP_LAST)',
       'Value (Cluster1.OGREY1_G1_KONTROLL_REG_NIVA_SP_TM_PV)',
       'Value (Cluster1.OGREY1_G1_KONTROLL_REG_P_SP_TM_PV)',
       'Value (Cluster1.OGREY1_G1_KONTROLL_AGC_DB_SP)'],
      dtype='object')

  Shortet the name of Columns:
    
    'Value (Cluster1.OGREY1_G1_KONTROLL_REG_P_SP_SP_LAST)'     changed to   'REG_P_LAST(KW)',     
    'Value (Cluster1.OGREY1_G1_KONTROLL_REG_NIVA_SP_SP_LAST)'  changed to   'REG_NIVA_LAST(m)',
    'Value (Cluster1.OGREY1_G1_KONTROLL_REG_NIVA_SP_TM_PV)'    changed to   'REG_NIVA_PV(m)',
    'Value (Cluster1.OGREY1_G1_KONTROLL_REG_P_SP_TM_PV)'       changed to   'REG_P_PV(KW)',
    'Value (Cluster1.OGREY1_G1_KONTROLL_AGC_DB_SP)'            changed to   'AGC_DB_SP',

    Since the unit columns were removed, the unit for each feature is appended to the column name in parentheses.

In [17]:
analys_historic_data.columns=['DateTime','REG_P_LAST(KW)', 'REG_NIVA_LAST(m)','REG_NIVA_PV(m)', 'REG_P_PV(KW)', 'AGC_DB_SP']
analys_historic_data.columns

Index(['DateTime', 'REG_P_LAST(KW)', 'REG_NIVA_LAST(m)', 'REG_NIVA_PV(m)',
       'REG_P_PV(KW)', 'AGC_DB_SP'],
      dtype='object')

In [ ]:

analys_historic_data.head()

,DateTime,REG_P_LAST(KW),REG_NIVA_LAST(m),REG_NIVA_PV(m),REG_P_PV(KW),AGC_DB_SP
0,2023-12-31 23:00:00.000,8200,"-0,5","-0,5",600,0
1,2024-01-01 00:00:00.000,8200,"-0,5","-0,5","4264,748807683333","5,475555462666667"
2,2024-01-01 01:00:00.000,8200,"-0,5","-0,5",5600,"5,599999905"
3,2024-01-01 02:00:00.000,8200,"-0,5","-0,5","5503,84444445","5,502222220116667"
4,2024-01-01 03:00:00.000,8200,"-0,5","-0,5",5500,"5,5"

In [20]:
#Creates a list of the columns you want to clean, exclude DateTime
#astype(str)  >> Converts values into text/string format
#.str.replace(',', '.') >> Changes decimal commas into decimal points.

cols=['REG_P_LAST(KW)','REG_NIVA_LAST(m)','REG_NIVA_PV(m)', 'REG_P_PV(KW)', 'AGC_DB_SP']
for col in cols:
    analys_historic_data[col] = analys_historic_data[col].astype(str).str.replace(',', '.', regex=False)
    analys_historic_data[col] = analys_historic_data[col].apply(pd.to_numeric, errors='coerce')    # Converts the cleaned text into numeric values (float64).

In [ ]:
# The DateTime column converted from object data type to datetime format

analys_historic_data['DateTime'] = pd.to_datetime(analys_historic_data['DateTime'], errors='coerce')

In [25]:
analys_historic_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8785 entries, 0 to 8784
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   DateTime          8785 non-null   datetime64[ns]
 1   REG_P_LAST(KW)    8650 non-null   float64
 2   REG_NIVA_LAST(m)  8651 non-null   float64
 3   REG_NIVA_PV(m)    5991 non-null   float64
 4   REG_P_PV(KW)      6663 non-null   float64
 5   AGC_DB_SP         8784 non-null   float64
dtypes: datetime64[ns](1), float64(5)
memory usage: 411.9 KB

In [ ]:
# Shows the numbe rof missing values for each column
analys_historic_data.isna().sum()

DateTime               0
REG_P_LAST(KW)       135
REG_NIVA_LAST(m)     134
REG_NIVA_PV(m)      2794
REG_P_PV(KW)        2122
AGC_DB_SP              1
dtype: int64

In [29]:
# estimates values from nearby timestamps
analys_historic_data = analys_historic_data.interpolate()

In [30]:
analys_historic_data.isna().sum()

DateTime            0
REG_P_LAST(KW)      0
REG_NIVA_LAST(m)    0
REG_NIVA_PV(m)      0
REG_P_PV(KW)        0
AGC_DB_SP           0
dtype: int64

In [31]:
analys_historic_data.head(5)

,DateTime,REG_P_LAST(KW),REG_NIVA_LAST(m),REG_NIVA_PV(m),REG_P_PV(KW),AGC_DB_SP
0,2023-12-31 23:00:00,8200.0,-0.5,-0.5,600.000000,0.000000
1,2024-01-01 00:00:00,8200.0,-0.5,-0.5,4264.748808,5.475555
2,2024-01-01 01:00:00,8200.0,-0.5,-0.5,5600.000000,5.600000
3,2024-01-01 02:00:00,8200.0,-0.5,-0.5,5503.844444,5.502222
4,2024-01-01 03:00:00,8200.0,-0.5,-0.5,5500.000000,5.500000

In [32]:
analys_historic_data.isna().sum()

DateTime            0
REG_P_LAST(KW)      0
REG_NIVA_LAST(m)    0
REG_NIVA_PV(m)      0
REG_P_PV(KW)        0
AGC_DB_SP           0
dtype: int64

In [33]:
# Check NaN
print(analys_historic_data.isna().sum().sum())

# Check empty strings
print((analys_historic_data== "").sum().sum())

0
0

In [ ]:
# Check for duplicate rows and columns

duplicate_rows = analys_historic_data.duplicated().sum()
duplicate_collumns = analys_historic_data.T.duplicated().sum()
print("Duplciate rows: ", duplicate_rows)
print("Duplicate columns: ", duplicate_collumns)

Duplciate rows:  0
Duplicate columns:  0

In [ ]:
analys_historic_data.to_csv(r"E:\code\Clean_HistData\final_Hist_data\cleaned_data.csv",index=False, sep=",")